name: Generate Manifest

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        type: string
        required: true
      release-note-url:
        description: 'Release Note URL'
        type: string
        required: true
      release-note-url-ja:
        description: 'Release Note (JA) URL'
        type: string
        required: true
  workflow_call:
    inputs:
      version:
        type: string
        required: true
      release-note-url:
        type: string
        required: true
      release-note-url-ja:
        type: string
        required: true

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get SHA256
        id: sha256
        run: |
          curl -fOL https://github.com/Floorp-Projects/Floorp/releases/download/v${{ inputs.version }}/floorp-win64.installer.exe
          echo "sha256-x64=$(sha256sum floorp-win64.installer.exe | cut -c 1-64 | tr '[:lower:]' '[:upper:]')" >> $GITHUB_OUTPUT
          curl -fOL https://github.com/Floorp-Projects/Floorp/releases/download/v${{ inputs.version }}/floorp-win32.installer.exe
          echo "sha256-x86=$(sha256sum floorp-win32.installer.exe | cut -c 1-64 | tr '[:lower:]' '[:upper:]')" >> $GITHUB_OUTPUT

      - name: Get ReleaseDate
        id: date
        run: |
          echo "releasedate=$( \
            curl -L \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ github.token }}" \
              https://api.github.com/repos/Floorp-Projects/Floorp/releases/tags/v${{ inputs.version }} \
            | jq -r '.published_at' \
            | cut -c 1-10 \
          )" >> $GITHUB_OUTPUT

      - name: Replace
        run: |
          sed -i 's/${version}/${{ inputs.version }}/g' ./stable/Ablaze.Floorp.installer.yaml
          sed -i 's/${version}/${{ inputs.version }}/' ./stable/Ablaze.Floorp.locale.en-US.yaml
          sed -i 's/${version}/${{ inputs.version }}/' ./stable/Ablaze.Floorp.locale.ja-JP.yaml
          sed -i 's/${version}/${{ inputs.version }}/' ./stable/Ablaze.Floorp.yaml
          sed -i s@'${releasenote-en}'@'${{ inputs.release-note-url }}'@ ./stable/Ablaze.Floorp.locale.en-US.yaml
          sed -i s@'${releasenote-ja}'@'${{ inputs.release-note-url-ja }}'@ ./stable/Ablaze.Floorp.locale.ja-JP.yaml
          sed -i 's/${releasedate}/${{ steps.date.outputs.releasedate }}/' ./stable/Ablaze.Floorp.installer.yaml
          sed -i 's/${x64sha}/${{ steps.sha256.outputs.sha256-x64 }}/' ./stable/Ablaze.Floorp.installer.yaml
          sed -i 's/${x86sha}/${{ steps.sha256.outputs.sha256-x86 }}/' ./stable/Ablaze.Floorp.installer.yaml

      #- id: yq-x64
      #  uses: mikefarah/yq@v4
      #  with:
      #    cmd: yq eval '.Installers.[] | select(.Architecture == "x64") | .InstallerURL' 'Ablaze.Floorp.installer.yml'
      #
      #- name: CalcHash & Replace
      #  run: |
      #    curl -OL ${{ steps.yq-x64.outputs.result }}

      - uses: actions/upload-artifact@v4
        with:
          name: manifest
          path: |
            ./stable/Ablaze.Floorp.installer.yaml
            ./stable/Ablaze.Floorp.locale.*.yaml
            ./stable/Ablaze.Floorp.yaml
