name: PR Daylight

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        type: string
        required: true

jobs:
  generate:
    uses: ./.github/workflows/gen-beta.yml
    with:
      version: ${{ inputs.version }}

  commit:
    needs: generate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/winget-pkgs
          sparse-checkout: |
            manifests/a/Ablaze
            .gitattributes
            .gitignore
          token: ${{ secrets.PAT }}

      - name: Pull & Push
        run: |
          git remote add upstream https://github.com/microsoft/winget-pkgs
          echo "::group::pull"
          git pull upstream master
          echo "::endgroup::"
          git push

      - name: Create branch
        run: |
          git branch Ablaze.Floorp.Daylight-${{ inputs.version }}
          git switch Ablaze.Floorp.Daylight-${{ inputs.version }}

      - name: Recreate directory
        run: |
          rm -rf manifests/a/Ablaze/Floorp/Daylight
          mkdir -pv manifests/a/Ablaze/Floorp/Daylight/${{ inputs.version }}

      - name: Download a Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: manifest
          path: manifests/a/Ablaze/Floorp/Daylight/${{ inputs.version }}

      - name: Commit & Push
        run: |
          git config --global user.email "${{ vars.GIT_EMAIL }}"
          git config --global user.name "${{ vars.GIT_NAME }}"
          git config --global core.autocrlf false
          git add .
          git commit -m "New version: Ablaze.Floorp.Daylight version ${{ inputs.version }}"
          git push --set-upstream origin Ablaze.Floorp.Daylight-${{ inputs.version }}

  pr:
    needs: commit
    runs-on: ubuntu-latest
    environment: 
      name: Deploy-Pull-Request
    steps:
      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          gh pr create \
            --repo https://github.com/microsoft/winget-pkgs \
            --base master \
            --head ${{ github.repository_owner }}:Ablaze.Floorp.Daylight-${{ inputs.version }} \
            --title "New version: Ablaze.Floorp.Daylight version ${{ inputs.version }}" \
            --body "### Pull request created by [Floorp-WinGet-Updater](https://github.com/${{ github.repository }}) workflow run [#${{ github.run_number }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }})"
