name: PR Stable
run-name: PR Stable ${{ inputs.tag-version }}

on:
  workflow_dispatch:
    inputs:
      tag-version:
        description: 'Tag Version (e.g., 12.6.0)'
        type: string
        required: true
      version:
        description: 'Version (e.g., 12.6.0@145.0.1)'
        type: string
        required: false
        default: ''
      releasenote-url-version:
        description: 'Release Note URL Version'
        type: string
        required: false
        default: ''

jobs:
  generate:
    uses: ./.github/workflows/gen.yml
    with:
      tag-version: ${{ inputs.tag-version }}
      version: ${{ inputs.version }}
      releasenote-url-version: ${{ inputs.releasenote-url-version }}

  commit:
    needs: generate
    runs-on: ubuntu-latest
    steps:
      #- uses: actions/create-github-app-token@v1
      #  id: app-token
      #  with:
      #    app-id: ${{ vars.APP_ID }}
      #    private-key: ${{ secrets.PRIVATE_KEY }}
      #- run: git push
      #  with:
      #    token: ${{ steps.app-token.outputs.token }}

      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/winget-pkgs
          sparse-checkout: |
            manifests/a/Ablaze
            .gitattributes
            .gitignore
          token: ${{ secrets.PAT }}

      - name: Pull & Push
        run: |
          git remote add upstream https://github.com/microsoft/winget-pkgs
          echo "::group::pull"
          git pull upstream master
          echo "::endgroup::"
          git push

      - name: Create branch
        run: |
          git branch Ablaze.Floorp-${{ inputs.tag-version }}
          git switch Ablaze.Floorp-${{ inputs.tag-version }}

      - name: Download a Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: manifest
          path: manifests/a/Ablaze/Floorp/${{ inputs.version || needs.generate.outputs.version }}

      - name: Commit & Push
        run: |
          git config --global user.email "${{ vars.GIT_EMAIL }}"
          git config --global user.name "${{ vars.GIT_NAME }}"
          git config --global core.autocrlf false
          git add .
          git commit -m "New version: Ablaze.Floorp version ${{ inputs.version || needs.generate.outputs.version }}"
          git push --set-upstream origin Ablaze.Floorp-${{ inputs.tag-version }}
          echo "${{ github.server_url }}/${{ github.repository_owner }}/winget-pkgs/tree/Ablaze.Floorp-${{ inputs.tag-version }}/" > $GITHUB_STEP_SUMMARY

  pr:
    needs: [generate, commit]
    runs-on: ubuntu-latest
    environment: 
      name: Deploy-Pull-Request
    steps:
      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.PAT_CLASSIC }}
        run: |
          gh pr create \
            --repo https://github.com/microsoft/winget-pkgs \
            --base master \
            --head ${{ github.repository_owner }}:Ablaze.Floorp-${{ inputs.tag-version }} \
            --title "New version: Ablaze.Floorp version ${{ inputs.version || needs.generate.outputs.version }}" \
            --body "### Pull request created by [Floorp-WinGet-Updater](https://github.com/${{ github.repository }}) workflow run [#${{ github.run_number }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }})" \
            --no-maintainer-edit \
            > $GITHUB_STEP_SUMMARY
