name: PR

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        type: string
        required: true
      release-note-url:
        description: 'Release Note URL'
        type: string
        required: true
      release-note-url-ja:
        description: 'Release Note (JA) URL'
        type: string
        required: true

jobs:
  generate:
    uses: ./.github/workflows/gen.yml
    with:
      version: ${{ inputs.version }}
      release-note-url: ${{ inputs.release-note-url }}
      release-note-url-ja: ${{ inputs.release-note-url-ja }}

  commit:
    needs: generate
    runs-on: ubuntu-latest
    steps:
      #- uses: actions/create-github-app-token@v1
      #  id: app-token
      #  with:
      #    app-id: ${{ vars.APP_ID }}
      #    private-key: ${{ secrets.PRIVATE_KEY }}
      #- run: git push
      #  with:
      #    token: ${{ steps.app-token.outputs.token }}

      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/winget-pkgs
          sparse-checkout: |
            manifests/a/Ablaze
            .gitattributes
            .gitignore
          token: ${{ secrets.PAT }}

      - name: Pull & Push
        run: |
          git remote add upstream https://github.com/microsoft/winget-pkgs
          echo "::group::pull"
          git pull upstream master
          echo "::endgroup::"
          git push

      - name: Create branch
        run: |
          git branch Ablaze.Floorp-${{ inputs.version }}
          git switch Ablaze.Floorp-${{ inputs.version }}

      - name: Download a Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: manifest
          path: manifests/a/Ablaze/Floorp/${{ inputs.version }}
