name: PR

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        type: string
        required: true

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      #- uses: actions/create-github-app-token@v1
      #  id: app-token
      #  with:
      #    app-id: ${{ vars.APP_ID }}
      #    private-key: ${{ secrets.PRIVATE_KEY }}
      #- run: git push
      #  with:
      #    token: ${{ steps.app-token.outputs.token }}

      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/winget-pkgs
          sparse-checkout: |
            manifests/a/Ablaze
            .gitattributes
            .gitignore
          token: ${{ secrets.PAT }}

      - name: Pull & Push
        run: |
          git remote add upstream https://github.com/microsoft/winget-pkgs
          echo "::group::pull"
          git pull upstream master
          echo "::endgroup::"
          git push

      - name: Create branch
        run: |
          git branch Ablaze.Floorp-${{ inputs.version }}
          git switch Ablaze.Floorp-${{ inputs.version }}
